name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet build JobOfferBackendDotNet.sln --configuration Release
      working-directory: .\JobOfferBackendDotNet
    - name: Installing MongoDB
      run: choco install mongodb
    - name: Installing Coverlet
      run: dotnet tool install --global coverlet.console
    - name: Runnig Tests and Code Coverage
      run: dotnet test .\JobOfferBackendDotNet\JobOfferBackendDotNet.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: d0yWm2f1f01JJKEH0H7q5tCq5OJtSUewV
        base-path: .\JobOfferBackendDotNet\
    
